name: Digger 

on:
  pull_request:
    branches:
      - digger-terragrunt-include-test
    types: [opened, synchronize]
  issue_comment:
    types: [created]

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write   # allow comment on PRs
      issues: write  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Digger with terragrunt include patterns fix
        uses: salsiy/digger@fix/terragrunt-include-patterns
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: "true"
        with:
          no-backend: true
          setup-terragrunt: true
          setup-terraform: true
          digger-spec: ${{ inputs.spec }}
          terraform-version: v1.5.7
          terragrunt-version: v0.73.7
          setup-aws: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          


