name: Digger 

on:
  push:
    branches:
      - digger-terragrunt-include-test

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Digger with terragrunt include patterns fix
        uses: salsiy/digger@fix/terragrunt-include-patterns
        env:
          DEBUG: "true"
        with:
          setup-terragrunt: true
          setup-terraform: true
          terraform-version: v1.5.7
          terragrunt-version: v0.73.7
          setup-aws: true
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          no-backend: true


